# Generated by Django 5.1.1 on 2024-11-11 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_rfid', '0002_alter_rfid_id_esp32_alter_rfid_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='idNFC',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.CreateModel(
            name='NFC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tag', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(max_length=50)),
                ('fecha_asignado', models.DateField()),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfid_set', to='data_rfid.product')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('movement_type', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('NFC_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_rfid.nfc')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stockmovements', to='data_rfid.product')),
            ],
        ),
    ]
