# Generated by Django 5.1.1 on 2024-11-13 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_rfid', '0003_remove_product_idnfc_remove_product_stock_nfc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rfid',
            old_name='id_tag',
            new_name='id_tagr',
        ),
    ]
